languageCode = "en-us"
title = "Adam Gefen"
baseURL = "https://thepaciellogroup.github.io/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "developer. Clojure. functional JS. elisp"
  codePenUser = "Heydon"
